apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb
spec:
  replicas: 1

  selector:
    matchLabels:
      app: mariadb

  template:
    metadata:
      labels:
        app: mariadb

    spec:
      containers:
        - name: mariadb
          image: "{{ .Values.mariadb.image.repository }}:{{ .Values.mariadb.image.tag }}"

          ports:
            - name: mysql
              containerPort: 3306

          env:
            - name: MYSQL_ROOT_PASSWORD
              value: killbill

          readinessProbe:
            exec:
              command:
                - mariadb-admin
                - ping
                - "-pkillbill"
            initialDelaySeconds: 30
            periodSeconds: 10
