:toc: macro
:toc-title:
:toclevels: 9

[[kill-bill-on-dcos]]
= Kill Bill on DC/OS

toc::[]

[[kill-bill-stack-installation]]
## Kill Bill stack installation

....
# Install the database
dcos marathon app add db-marathon.json

# Install Kill Bill
dcos marathon app add kb-marathon.json

# Install public load balancer for Kaui
dcos package install --options=marathon-lb-external.json marathon-lb

# Install Kaui
dcos marathon app add kaui-marathon.json

# Find public node IP
DCOS_PUBLIC_IP=`for id in $(dcos node --json | jq --raw-output '.[] | select(.attributes.public_ip == "true") | .id'); do dcos node ssh --option StrictHostKeyChecking=no --option LogLevel=quiet --master-proxy --mesos-id=$id "curl -s ifconfig.co" ; done 2>/dev/null`
....

Go to `$DCOS_PUBLIC_IP:10080` to log-in to Kaui.

[[metrics-stack-installation]]
## Metrics stack installation

....
# Install cAdvisor
dcos marathon app add cadvisor-marathon.json

# Install InfluxDB
dcos marathon app add influxdb-marathon.json

# Install Grafana
dcos marathon app add grafana-marathon.json
....

Go to `$DCOS_PUBLIC_IP:10030` to log-in to Grafana.

[[vips]]
## VIPs

* Database: `killbill-db.marathon.l4lb.thisdcos.directory:3306` (internal)
* Kill Bill: `http://killbill.marathon.l4lb.thisdcos.directory:8080` (internal)
* Kaui: `http://marathon-lb-external.marathon.mesos:10080` (internal), `$DCOS_PUBLIC_IP:10080` (external)
* Grafana: `http://marathon-lb-external.marathon.mesos:10030` (internal), `$DCOS_PUBLIC_IP:10030` (external)
