# Metrics stack
version: '3.2'
volumes:
  influxdb:
services:
  influxdb:
    image: influxdb:1.8.3-alpine
    volumes:
      - type: volume
        source: influxdb
        target: /var/lib/influxdb
    ports:
      - "8083:8083"
      - "8086:8086"
    environment:
      - INFLUXDB_ADMIN_USER=killbill
      - INFLUXDB_ADMIN_PASSWORD=killbill
      - INFLUXDB_USER=killbill
      - INFLUXDB_USER_PASSWORD=killbill
      - INFLUXDB_DB=killbill
  grafana:
    image: grafana/grafana:7.2.0
    ports:
      - "3000:3000"
    depends_on:
      - influxdb
