:toc: macro
:toc-title:
:toclevels: 9

[[docker-compose-recipes]]
# docker-compose recipes

toc::[]

## Quick start

https://docs.docker.com/compose/[Docker Compose] is the easiest way to set up the Kill Bill stack:

```
docker-compose -f docker-compose.kb.yml -p kb up
```

Note: if you are using Docker Machine, use `docker-machine env <name>` or the environment variable `$DOCKER_HOST` to get the IP address of the container.

Then go to `http://<IP_ADDRESS>:9090/` and log-in via `admin/password`.

In the rest of this documentation, we will assumed `IP_ADDRESS` is 127.0.0.1.

## Logging and Metrics infrastructure

[[logging]]
### Logging

Refer to the https://www.elastic.co/guide/index.html[Elastic Stack] documentation for how to set up the ELK stack.

Here's a quick tutorial to get you started:

* Clone https://github.com/deviantony/docker-elk
* Update `logstash/pipeline/logstash.conf` and enable the Logstash JSON codec:
```
diff --git a/logstash/pipeline/logstash.conf b/logstash/pipeline/logstash.conf
index 40ca757..6ccbfb2 100644
--- a/logstash/pipeline/logstash.conf
+++ b/logstash/pipeline/logstash.conf
@@ -5,6 +5,7 @@ input {

        tcp {
                port => 5000
+               codec => json
        }
 }
```
* Run `docker-compose up` to start the stack. This takes a while. You can verify the stack is up by going to http://127.0.0.1:9200/ (user: elastic, password: changeme)
* Once the stack is up, redirect the Kill Bill container logs to Logstash using Logspout:
```
docker run --name="logspout" \
           --volume=/var/run/docker.sock:/var/run/docker.sock \
           gliderlabs/logspout \
           'tcp://host.docker.internal:5000?filter.name=kb_killbill_1'
```
* Go to Kibana at http://127.0.0.1:5601/ (user: elastic, password: changeme)
* Create an index pattern by going to http://127.0.0.1:5601/app/management/kibana/indexPatterns/create: enter `logstash-*` in the first screen and select `@timestamp` as the time filter field
* Go to `http://127.0.0.1:5601/app/discover` to visualize the Kill Bill logs

Notes:

* You need Docker Engine version 17.05 or newer and Docker Compose version 1.20.0 or newer
* You need at least 4GB of RAM allocated to Docker to run the entire stack

[[monitoring]]
### Metrics

The `docker-compose.gi.yml` file sets up Telegraf, InfluxDB, cAdvisor and Grafana.

The Grafana UI is available at `http://<IP_ADDRESS>:3000` (default credentials: `admin:admin`).

When running the full stack, Grafana uses the MariaDB container as the storage backend. To configure it (default database credentials `root:killbill`):

....
CREATE DATABASE grafana;
USE grafana;
CREATE TABLE `session` (
    `key`       CHAR(16) NOT NULL,
    `data`      BLOB,
    `expiry`    INT(11) UNSIGNED NOT NULL,
    PRIMARY KEY (`key`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
....

You also need to add the InfluxDB datasources. Got to http://<IP_ADDRESS>:3000/datasources/new:

* Name: influxdb
* Type: InfluxDB
* Url: http://influxdb:8086
* Database: killbill
* User: killbill
* Password: killbill
