name: kpm_rubocop

on: [push, pull_request, workflow_dispatch]

jobs:
  kpm_rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.8
          bundler-cache: true
          working-directory: kpm
      - name: Run RuboCop
        run: |
          cd kpm
          bundle exec rubocop --parallel
